spring.application.name=backend

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/sgtg}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:oracle}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
spring.jpa.hibernate.ddl-auto=create-drop

# Security configuration
#spring.security.user.name=${SPRING_SECURITY_USER_NAME:root}
#spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:root}
#spring.security.user.roles={ROLE_VIEWER}

# JWT configuration
jwt.secret=${JWT_SECRET:5kMpK8pN2vQ9rX3sT6uW1yZ4aB7cD0eF3gH6iJ9lM2n5pOqRsT}

# Prints the exact SQL queries to the console log
spring.jpa.show-sql=true

# Formats the printed console SQL output cleanly
spring.jpa.properties.hibernate.format_sql=true

# Highlights standard SQL commands in the console log via colors
spring.jpa.properties.hibernate.highlight_sql=true

# Logs the internal parameter bound variables used during execution
logging.level.org.hibernate.orm.jdbc.bind=trace
