spring.application.name=backend

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/sgtg}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:oracle}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

# Security configuration
#spring.security.user.name=${SPRING_SECURITY_USER_NAME:root}
#spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:root}
#spring.security.user.roles={ROLE_VIEWER}
